name: Cargo Clippy

on:
  push:

jobs:
  ci:
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v3
      - name: Install Nix
        uses: DeterminateSystems/nix-installer-action@v4
      - name: Test
        run: cargo clippy --all-targets --all-features -- -D warnings
